yaml buildCommand updated

diff --git a/render.yaml b/render.yaml
--- a/render.yaml
+++ b/render.yaml
@@ -12,8 +12,10 @@ services:
       export DEBUG=False
       pip install --upgrade pip
       pip install -r requirements.txt
-      rm -rf reroute_business/staticfiles  # match STATIC_ROOT path
-      python manage.py collectstatic --noinput --verbosity 2 || (echo "Collectstatic failed!" && exit 1)
+      cd reroute_business          # 👈 ensure we're in the correct directory
+      rm -rf staticfiles
+      python ../manage.py collectstatic --noinput --verbosity 2 || (echo "Collectstatic failed!" && exit 1)
+
 
     preDeployCommand: |
       export PYTHONPATH=/opt/render/project/src
